monitor.alsa.rules = [
  { matches = [ { node.name = "~alsa_output.*HiFi__Headphones__sink" } ]
    actions = { update-props = { node.description = "Headphones (3.5mm jack)" } } }

  { matches = [ { node.name = "~alsa_output.*HiFi__Speaker__sink" } ]
    actions = { update-props = { node.description = "Laptop Speakers" } } }

  { matches = [ { node.name = "~alsa_input.*HiFi__Mic2__source" } ]
    actions = { update-props = { node.description = "Internal Microphone" } } }

  { matches = [ { node.name = "~alsa_input.*HiFi__Mic1__source" } ]
    actions = { update-props = { node.description = "Internal Microphone (digital)" } } }

  { matches = [ { node.name = "~alsa_output.*HiFi__HDMI1__sink" } ]
    actions = { update-props = { node.description = "External Display 1 (DP/HDMI)" } } }

  { matches = [ { node.name = "~alsa_output.*HiFi__HDMI2__sink" } ]
    actions = { update-props = { node.description = "External Display 2 (DP/HDMI)" } } }

  { matches = [ { node.name = "~alsa_output.*HiFi__HDMI3__sink" } ]
    actions = { update-props = { node.description = "External Display 3 (DP/HDMI)" } } }
]
